export apiAuth from './Auth/Auth'
export apiCompanies from './Companies/Companies'
export apiConversations from './Conversations/Conversations'
export apiDemands from './Demands/Demands'
export apiSegments from './Segments/Segments'
export apiServices from './Services/Services'
